name: build

on:
  workflow_dispatch:

jobs:
  build-webassembly:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt Archive
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ~/qt-everywhere-src-6.5.2.tar
          key: qt-everywhere-src-6.5.2.tar
          restore-keys: |
            qt-everywhere-src-6.5.2-
      - name: Download Qt if not Cached
        run: |
          if [ ! -f "~/qt-everywhere-src-6.5.2.tar" ]; then
            curl -L -o ~/qt-everywhere-src-6.5.2.tar.xz "https://download.qt.io/archive/qt/6.5/6.5.2/single/qt-everywhere-src-6.5.2.tar.xz"
            cd ~
            gunzip qt-everywhere-src-6.5.2.tar.xz
          fi
      - name: Build Qt Host Version
        run: |
          cd ~
          tar xf qt-everywhere-src-6.5.2.tar
          cd qt-everywhere-src-6.5.2
          ./configure
          cmake --build . --parallel
      - name: Install emsdk
        run: |
          cd ~
          git clone https://github.com/emscripten-core/emsdk.git
          cd ~/emsdk
          ./emsdk install 3.1.25
          ./emsdk activate 3.1.25
      - name: Build Qt WebAssembly Version
        run: |
          cd ~
          mkdir qt-everywhere-src-6.5.2-webassembly
          tar xf qt-everywhere-src-6.5.2.tar -C ./qt-everywhere-src-6.5.2-webassembly
          cd ~/qt-everywhere-src-6.5.2-webassembly/qt-everywhere-src-6.5.2
          source ~/emsdk/emsdk_env.sh
          ./configure -feature-thread -qt-host-path ~/qt-everywhere-src-6.5.2/qtbase -platform wasm-emscripten -prefix $PWD/qtbase
          cmake --build . --parallel -t qtbase -t qtdeclarative -t qtimageformats -t qtsvg
      - name: Build Dust3D Webassembly
        run: |
          cd ~
          git clone https://github.com/huxingyi/dust3d.git
          cd ~/dust3d
          source ~/emsdk/emsdk_env.sh
          ~/qt-everywhere-src-6.5.2-webassembly/qt-everywhere-src-6.5.2/qtbase/bin/qmake
          make -j`nproc`
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: web.dust3d.org
          path: |
            ~/dust3d/application/dust3d.html
            ~/dust3d/application/dust3d.js
            ~/dust3d/application/dust3d.wasm
            ~/dust3d/application/dust3d.worker.js
            ~/dust3d/application/qtloader.js